accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    path('login/', views.login_user, name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('signup/', views.create_user, name='signup'),
]

discussion/urls.py
from django.urls import path
from .import views
app_name = "discussion"

urlpatterns = [
    path('create/', views.create_post, name="createpost"),
    path('', views.home, name="home"),
    path('userposts/<int:pk>', views.userposts, name="userposts"),
    path('post/<int:pk>', views.post, name="post"),
    path('<int:pk>/upvote', views.upvote, name='upvote'),
    path('<int:pk>/downvote', views.downvote, name='downvote'),
]

forum/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from . import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('accounts/',include('accounts.urls',namespace="accounts")),
    path('discussion/',include('discussion.urls',namespace="discussion")),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/partials/footer.html
<footer class="footer mt-auto p-2 bg-primary"data-bs-theme="dark">
    <h3 class="text-center">Connect with us</h3>
    <div
      class="d-flex justify-content-evenly flex-wrap"
    >
      <a href="https://www.linkedin.com/in/vishalkumar32/" target="_blank">
        <i class="fab fa-linkedin-in fa-3x"></i>
      </a>
      <a
        class="text-decoration-none"
        href="https://github.com/vishalkumar32"
        target="_blank"
      >
        <i class="fab fa-github fa-3x"></i>
      </a>
      <a href="https://twitter.com/" target="_blank">
        <i class="fab fa-twitter fa-3x"></i>
      </a>
      <a href="https://www.instagram.com/vi.shalrathod979/" target="_blank">
        <i class="fab fa-instagram fa-3x"></i>
      </a>
    </div>
</footer>
  

templates/partials/navbar.html
<nav class="navbar navbar-expand-lg bg-primary" data-bs-theme="dark">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'home' %}">Home</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbar-nav" aria-controls="navbar-nav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbar-nav">
        <ul class="navbar-nav me-auto">
          <li class="nav-item">
            <a class="nav-link active" href="{% url 'discussion:home' %}">Posts</a>
          </li>
        </ul>
        <div class="navbar-nav">
        {% if request.user.is_authenticated %}
        <a class="nav-link active float-right" href="{% url 'discussion:createpost' %}">Post+</a>
        <a class="nav-link active float-right" href="{% url 'discussion:userposts' request.user.id %}">MyPosts</a>
        <a class="nav-link active" href="{% url 'accounts:logout' %}">Logout</a>
        {% else %}
            <a class="nav-link active float-right" href="{% url 'accounts:login' %}">Login</a>
            <a class="nav-link active float-right" href="{% url 'accounts:signup' %}">Signup</a>
        {% endif %}
        </div>
      </div>
    </div>
  </nav>