discussion/urls.py
from django.urls import path
from .import views
app_name = "discussion"

urlpatterns = [
    path('create/', views.create_post, name="createpost"),
    path('', views.home, name="home"),
    path('userposts/<int:pk>', views.userposts, name="userposts"),
    path('post/<int:pk>', views.post, name="post"),
    path('<int:pk>/upvote', views.upvote, name='upvote'),
    path('<int:pk>/downvote', views.downvote, name='downvote'),
]

forum/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from . import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('accounts/',include('accounts.urls',namespace="accounts")),
    path('discussion/',include('discussion.urls',namespace="discussion")),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

discussion/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
# Create your models here.


class Post(models.Model):
    title = models.CharField(max_length=255)
    url = models.URLField(default=None)
    description = models.TextField()
    image = models.ImageField(upload_to='images/', default=None)
    pub_date = models.DateTimeField(default=timezone.now)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    votes = models.IntegerField(default=1)

    def __str__(self):
        return f"{self.author.username}-{self.title[:25]}"

    def pub_date_pretty(self):
        return self.pub_date.strftime('%b %e %Y')


class Contact(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    email = models.EmailField(max_length=254)
    subject = models.CharField(max_length=255)
    message = models.TextField()

    def __str__(self) -> str:
        return f"{self.user.username}-{self.subject[:25]}"


class Vote(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    voter = models.ForeignKey(User, on_delete=models.CASCADE)
    # upvote=models.BooleanField()

    def __str__(self):
        return f"{self.post.title[:25]}-{self.voter.username}"

discussion/forms.py
from django import forms

from .models import Post, Contact


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'url', 'description', 'image']
        # fields = '__all__'
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control my-2', 'placeholder': 'Enter title'},),
            'url': forms.URLInput(attrs={'class': 'form-control my-2', 'placeholder': 'Enter related link'},),
            'description': forms.Textarea(attrs={'class': 'form-control my-2', 'placeholder': 'Please describe'},),
            'img': forms.ClearableFileInput(attrs={'class': 'form-control my-2', 'type': 'file'},),
        }


class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        # fields = '__all__'
        fields = ['name', 'email', 'subject', 'message']
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control my-2', 'placeholder': 'Enter name'},),
            'email': forms.EmailInput(attrs={'class': 'form-control my-2', 'placeholder': 'Enter email'},),
            'subject': forms.TextInput(attrs={'class': 'form-control my-2', 'placeholder': 'Enter subject'},),
            'message': forms.Textarea(attrs={'class': 'form-control my-2', 'placeholder': 'Enter message', },),
        }

discussion/views.py
from django.shortcuts import render, redirect
from .forms import PostForm
from django.contrib import messages
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from .models import Post, Vote
from django.core.paginator import Paginator
# Create your views here.


@login_required
def create_post(request):
    form = PostForm()

    if request.method == "POST":
        form = PostForm(request.POST, files=request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            # form.save()
            messages.success(request, "Post created successfully!!",
                             extra_tags='alert alert-success alert-dismissible fade show')
            # return redirect('discussion:createpost')
        else:
            messages.error(request, "Oops someting is missing,please try angain!!",
                           extra_tags='alert alert-warning alert-dismissible fade show')

    context = {
        'form': form,
    }
    return render(request, 'discussion/create.html', context)


def home(request):
    posts = Post.objects.all()
    search_term = ''
    try:
        if 'name' in request.GET:
            posts = posts.order_by('title')

        if 'date' in request.GET:
            posts = posts.order_by('pub_date')

        if 'vote' in request.GET:
            posts = posts.order_by('-votes')

        if 'search' in request.GET:
            search_term = request.GET['search']
            posts = posts.filter(text__icontains=search_term)
    except:
        pass
    paginator = Paginator(posts, 6)
    page = request.GET.get('page')
    posts = paginator.get_page(page)

    dict = request.GET.copy()
    params = dict.pop('page', True) and dict.urlencode()
    return render(request, 'discussion/home.html', {'posts': posts, 'params': params, 'search_term': search_term})


@login_required
def upvote(request, pk):
    if request.method == 'POST':
        post = Post.objects.get(pk=pk)
        user = request.user

        try:
            if Vote.objects.filter(post=post, voter=user).exists():
                # post.votes -= 1
                # vote = Vote.objects.filter(post=post, voter=user)
                # vote.delete()
                pass
            else:
                Vote.objects.create(post=post, voter=user)
                post.votes += 1
                post.save()
        except:
            pass
        next = request.POST.get('next', '/')
        return redirect(next)


@login_required
def downvote(request, pk):
    if request.method == 'POST':
        post = Post.objects.get(pk=pk)
        user = request.user
        try:
            if Vote.objects.filter(post=post, voter=user).exists():
                # post.votes += 1
                # vote = Vote.objects.filter(post=post, voter=user)
                # vote.delete()
                pass
            else:
                Vote.objects.create(post=post, voter=user)
                post.votes -= 1
                post.save()
        except:
            pass
        next = request.POST.get('next', '/')
        return redirect(next)


@login_required
def userposts(request, pk):
    posts = Post.objects.filter(author__id=pk).order_by('-pub_date')
    paginator = Paginator(posts, 6)
    page = request.GET.get('page')
    posts = paginator.get_page(page)

    dict = request.GET.copy()
    params = dict.pop('page', True) and dict.urlencode()
    author = User.objects.get(pk=pk)
    return render(request, 'discussion/userposts.html', {'posts': posts, 'author': author, 'params': params})


@login_required
def post(request, pk):
    post = Post.objects.filter(id=pk)
    return render(request, 'discussion/detail.html', {'post': post})

templates/discussion/create.html
{% extends 'base.html' %}

{% block title %}   
    Create new post
{% endblock title %}

{% block content %}
<div class="container d-flex flex-column justify-content-center my-4 flex-wrap">
    <h3 class="text-center my-2">New Post</h3>
    <div class="row center">
        <div class="col-md-6 offset-md-3">
            {% if messages %}
            <div class="messages">
                {% for message in messages %}
                <div {% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
                {% endfor %}
            </div>
            {% endif %}
            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-primary">Submit</button>
                <button type="submit" class="btn btn-danger"><a href="../create" class="text-decoration-none text-light">Clear</a></button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

templates/discussion/detail.html
{% extends 'base.html' %}
{% block title %}
{% for post in post %}   
    {{post.title}}
{% endfor %}
{% endblock title %}
{% block content %}

{% if post %}
<div class="container d-flex justify-content-center flex-wrap my-4">
    {% for post in post %}
      {% if post.image %}
            <img src="{{ post.image.url }}" class="card-img-top" alt="{{ post.title}}" style="width: 18rem;">
      {% else %}
        <img src="..." class="card-img-top" alt="...">
      {% endif %}
      <div class="text-center">
        <a class="text-decoration-none" href="{{ post.url }}" target="_blank"><h6 class="card-title text-wrap"> {{ post.title}} </h6></a>
        <span>
          <button class="btn btn-primary btn-sm" onClick="document.getElementById('upvote{{ post.id }}').submit()">🔺</button>
          {{ post.votes }}
          <button class="btn btn-secondary btn-sm" onClick="document.getElementById('downvote{{ post.id }}').submit()">🔻</button>
        </span>
        <p class="text-wrap">{{post.description}}</p>
        
        <span>
          Author- <a class="text-decoration-none" href="{% url 'discussion:userposts' post.author.id %}">{{ post.author.username }}</a>
        </span>
        <span>
          Date- {{ post.pub_date_pretty }} 
        </span>
      </div>
    <form id="upvote{{ post.id }}" method="post" action="{% url 'discussion:upvote' post.id %}">
      {% csrf_token %}
      <input type="hidden" name="next" value="{{ request.path }}"/>
    </form>
    <form id="downvote{{ post.id }}" method="post" action="{% url 'discussion:downvote' post.id %}">
     {% csrf_token %}
     <input type="hidden" name="next" value="{{ request.path }}"/>
    </form>
    {% endfor %}
    {% else %}
    <div style="height: 22rem;">
      <h1 class="text-center my-4">No post found</h1>
    </div>
    {% endif %}
</div>  
{% endblock content %}
    

templates/discussion/home.html
{% extends 'base.html' %}

{% block title %}   
    Welcome to the Discussion page
{% endblock title %}

{% block content %}

{% if posts %}
<div class="row my-4">
  <div class="col-md-8 offset-sm-2">
<!-- Nav for home page -->
<a class="btn btn-{% if 'name' in request.GET %}secondary{% else %}primary{% endif %} mb-3" href="?name=True"
role="button"><i class="fas fa-sort-alpha-down"></i>
Name</a>
<a class="btn btn-{% if 'date' in request.GET %}secondary{% else %}primary{% endif %} mb-3" href="?date=True"
role="button"><i class="far fa-clock"></i> Date</a>
<a class="btn btn-{% if 'vote' in request.GET %}secondary{% else %}primary{% endif %} mb-3" href="?vote=True"
role="button"><i class="fas fa-poll"></i> Vote</a>    
<a class="btn btn-success mb-3 float-end" href="{% url 'discussion:createpost' %}" role="button">Create <i class="fas fa-plus"></i></a>
<!-- Nav for home page -->

</div>
</div>

<div class="container d-flex justify-content-center flex-wrap my-4">
    {% for post in posts %}
    <div class="card m-3" style="width: 18rem;">
      {% if post.image %}
            <img src="{{ post.image.url }}" class="card-img-top" alt="{{ post.title}}">
      {% else %}
        <img src="..." class="card-img-top" alt="...">
      {% endif %}
      <div class="card-body text-center">
        <a class="text-decoration-none" href="{{ post.url }}" target="_blank"><h6 class="card-title text-wrap"> {{ post.title|truncatewords:11 }} </h6></a>
        <span>
          <button class="btn btn-primary btn-sm" onClick="document.getElementById('upvote{{ post.id }}').submit()">🔺</button>
          {{ post.votes }}
          <button class="btn btn-secondary btn-sm" onClick="document.getElementById('downvote{{ post.id }}').submit()">🔻</button>
        </span>
        <p class="card-text text-wrap">{{post.description|truncatewords:25}}</p>
        
        <span>
          Author- <a class="text-decoration-none" href="{% url 'discussion:userposts' post.author.id %}">{{ post.author.username }}</a>
        </span>
        <span>
          Date- {{ post.pub_date_pretty }} 
        </span>
       
        <a href="{% url 'discussion:post' post.id %}" class="btn btn-primary">More</a>
      </div>
    </div>
    <form id="upvote{{ post.id }}" method="post" action="{% url 'discussion:upvote' post.id %}">
      {% csrf_token %}
      <input type="hidden" name="next" value="{{ request.path }}"/>
    </form>
    <form id="downvote{{ post.id }}" method="post" action="{% url 'discussion:downvote' post.id %}">
     {% csrf_token %}
     <input type="hidden" name="next" value="{{ request.path }}"/>
    </form>
    {% endfor %}
    {% else %}
    <div style="height: 22rem;">
      <h1 class="text-center my-4">No post found</h1>
    </div>
    {% endif %}
</div>

<div class="container d-flex justify-content-center flex-wrap">
  <div class="mt-3">
    <ul class="pagination">
      {% if posts.has_previous %}
      <li class="page-item"><a class="page-link" href="?page=1&{{ params }}">First</a></li>
      <li class="page-item"><a class="page-link" href="?page={{ posts.previous_page_number }}&{{ params }}">Previous</a></li>
      {% endif %}
      
      <li class="page-item active"><a class="page-link" href="">{{ posts.number }}</a></li>
      
      {% if posts.has_next %}
      <li class="page-item"><a class="page-link" href="?page={{ posts.next_page_number }}&{{ params }}">Next</a></li>
      <li class="page-item"><a class="page-link" href="?page={{ posts.paginator.num_pages }}&{{ params }}">Last</a></li>
      {% endif %}
    </ul>
  </div>
</div>
  
  
  {% endblock content %}
  

templates/discussion/userposts.html
{% extends 'base.html' %}

{% block title %}   
    All post by {{ author.username }}
{% endblock title %}

{% block content %}

{% if posts %}
<h1 class="text-center my-4"> All Posts By {{ author.username }} </h1>
<div class="container d-flex justify-content-center flex-wrap my-4">
    {% for post in posts %}
    <div class="card m-4" style="width: 18rem;">
      {% if post.image %}
            <img src="{{ post.image.url }}" class="card-img-top" alt="{{ post.title}}">
      {% else %}
        <img src="..." class="card-img-top" alt="...">
      {% endif %}
      <div class="card-body text-center">
        <a class="text-decoration-none" href="{{ post.url }}" target="_blank"><h6 class="card-title text-wrap"> {{ post.title|truncatewords:11 }} </h6></a>
        <span>
          <button class="btn btn-primary btn-sm" onClick="document.getElementById('upvote{{ post.id }}').submit()">🔺</button>
          {{ post.votes }}
          <button class="btn btn-secondary btn-sm" onClick="document.getElementById('downvote{{ post.id }}').submit()">🔻</button>
        </span>
        <p class="card-text text-wrap">{{post.description|truncatewords:25}}</p>
        
        <span>
          Author- <a class="text-decoration-none" href="{% url 'discussion:userposts' post.author.id %}">{{ post.author.username }}</a>
        </span>
        <span>
          Date- {{ post.pub_date_pretty }} 
        </span>
       
        <a href="{% url 'discussion:post' post.id %}" class="btn btn-primary">More</a>
      </div>
    </div>
    <form id="upvote{{ post.id }}" method="post" action="{% url 'discussion:upvote' post.id %}">
      {% csrf_token %}
      <input type="hidden" name="next" value="{{ request.path }}"/>
    </form>
    <form id="downvote{{ post.id }}" method="post" action="{% url 'discussion:downvote' post.id %}">
     {% csrf_token %}
     <input type="hidden" name="next" value="{{ request.path }}"/>
    </form>
    {% endfor %}
    {% else %}
    <div style="height: 22rem;">
      <h1 class="text-center my-4">No post found</h1>
    </div>
    {% endif %}
</div>

<div class="container d-flex justify-content-center flex-wrap">
  <nav class="mt-3">
    <ul class="pagination">
      {% if posts.has_previous %}
      <li class="page-item"><a class="page-link" href="?page=1&{{ params }}">First</a></li>
      <li class="page-item"><a class="page-link" href="?page={{ posts.previous_page_number }}&{{ params }}">Previous</a></li>
      {% endif %}
      
      <li class="page-item active"><a class="page-link" href="">{{ posts.number }}</a></li>
      
      {% if posts.has_next %}
      <li class="page-item"><a class="page-link" href="?page={{ posts.next_page_number }}&{{ params }}">Next</a></li>
      <li class="page-item"><a class="page-link" href="?page={{ posts.paginator.num_pages }}&{{ params }}">Last</a></li>
      {% endif %}
    </ul>
  </nav>
</div>
{% endblock %}